import {useEffect,useState}from'react';import*as I from'lucide-react';import {useGame}from'../store';import {provinces,tr}from'../data/content';import type{AppId,State}from'../core/model';
const timeOfDay=(v:string)=>{const h=new Date(v).getUTCHours();return h<10?'morning':h<17?'day':h<21?'evening':'night'};const money=(n:number)=>new Intl.NumberFormat('tr-TR',{style:'currency',currency:'TRY'}).format(n/100);const date=(s:string,o?:Intl.DateTimeFormatOptions)=>new Intl.DateTimeFormat('tr-TR',o||{dateStyle:'medium'}).format(new Date(s));
const appMeta:Record<AppId,[string,typeof I.Home,string]>={home:['Ana Ekran',I.Home,'#2f6e57'],archive:['Hayat Arşivi',I.BookHeart,'#9c6f47'],school:['Okulum',I.GraduationCap,'#3e70a8'],career:['Kariyer',I.BriefcaseBusiness,'#566f62'],bank:['CepBanka',I.WalletCards,'#2d7b68'],market:['SarıPazar',I.Store,'#c18c32'],chat:['Sohbet',I.MessageCircle,'#498665'],feed:['Akış',I.Rss,'#9b6655'],mail:['Posta',I.Mail,'#5479a5'],news:['Gündem',I.Newspaper,'#6b625b'],stocks:['Piyasa',I.ChartNoAxesCombined,'#39745c'],calendar:['Takvim',I.CalendarDays,'#aa5b4e'],map:['Harita',I.MapPinned,'#4f8277'],notes:['Notlar',I.NotebookPen,'#b5964b'],settings:['Ayarlar',I.Settings,'#70756f']};
export function App(){const s=useGame(),refresh=s.refresh,load=s.load;useEffect(()=>{void (async()=>{await refresh();const current=useGame.getState();if(!current.game&&current.lives[0])await load(current.lives[0].id)})()},[refresh,load]);if(s.screen==='menu')return <Menu/>;if(s.screen==='new')return <NewLife/>;if(s.screen==='lives')return <Lives/>;return <Device/>}
function Brand(){return <div className="brand"><span>M</span><div><b>MemleketOS</b><small>Bir hayat. Bin ihtimal.</small></div></div>}
function Menu(){const set=useGame(x=>x.setScreen);return <main className="menu"><div className="menu-panel"><Brand/><div className="menu-copy"><p>Türkiye’de sıradan bir hayatın olağanüstü ayrıntıları.</p><h1>Kendi ritminde<br/>bir hayat yaşa.</h1></div><nav><button className="primary" onClick={()=>set('new')}><I.Sparkles/> {tr.menu.newLife}</button><button onClick={()=>set('lives')}><I.Library/> {tr.menu.lives}</button></nav><small className="local"><I.ShieldCheck/> Tamamen yerel • Hesap yok • İzleme yok</small></div></main>}
function NewLife(){const s=useGame(),[name,setName]=useState(''),[province,setProvince]=useState('İstanbul');return <main className="form-page"><section><button className="back" onClick={()=>s.setScreen('menu')}><I.ArrowLeft/> Geri</button><p className="eyebrow">YENİ BİR BAŞLANGIÇ</p><h1>Hikâyen nerede başlıyor?</h1><p>Gerçek bilgi vermene gerek yok. Her ayrıntı cihazında ve tohumdan üretilir.</p><label>Karakter adı <input autoFocus value={name} onChange={e=>setName(e.target.value)} placeholder="Örn. Deniz Kaya"/></label><label>Başlangıç ili <select value={province} onChange={e=>setProvince(e.target.value)}>{provinces.map(p=><option key={p}>{p}</option>)}</select></label><button className="primary wide" onClick={()=>void s.newLife(name,province)}><I.Play/> Hayatı başlat</button></section></main>}
function Lives(){const s=useGame();const refresh=s.refresh;useEffect(()=>{void refresh()},[refresh]);return <main className="form-page"><section className="lives"><button className="back" onClick={()=>s.setScreen('menu')}><I.ArrowLeft/> Menü</button><h1>Hayatlarım</h1>{!s.lives.length&&<p>Henüz yerel kayıt yok.</p>}{s.lives.map(l=><article key={l.id}><div><b>{l.name}</b><small>{l.province} • {date(l.updatedAt)}</small></div><button onClick={()=>void s.load(l.id)}>Devam et</button><button className="danger" aria-label="Sil" onClick={()=>void s.remove(l.id)}><I.Trash2/></button></article>)}</section></main>}
function Device(){
  const s=useGame(),g=s.game!,[locked,setLocked]=useState(true),[center,setCenter]=useState(false),[timeOpen,setTimeOpen]=useState(false);
  if(locked)return <LockScreen g={g} unlock={()=>setLocked(false)}/>;
  return <main className={`device ${g.settings.largeText?'large':''} wallpaper-${g.settings.wallpaper} tod-${timeOfDay(g.now)}`}>
    <DesktopRail/><section className="workspace"><Status openCenter={()=>setCenter(true)}/><div className={`app-window app-${s.app}`}><AppHeader/><AppContent g={g} openTime={()=>setTimeOpen(true)}/></div><SystemNavigation/></section>
    {center&&<NotificationCenter g={g} close={()=>setCenter(false)}/>} {timeOpen&&<TimeSheet g={g} close={()=>setTimeOpen(false)}/>} {s.error&&<div role="alert" className="toast">{s.error}<button onClick={()=>s.setError()}>×</button></div>}
  </main>
}
function PhoneIndicators(){return <span className="indicators" aria-hidden="true"><I.Signal/><I.Wifi/><i className="battery"/></span>}
function LockScreen({g,unlock}:{g:State;unlock:()=>void}){const next=g.events.filter(e=>!e.processed).sort((a,b)=>a.at.localeCompare(b.at))[0];return <main className={`lock-screen wallpaper-${g.settings.wallpaper} tod-${timeOfDay(g.now)}`}>
  <div className="lock-status"><span>{new Date(g.now).toLocaleTimeString('tr-TR',{hour:'2-digit',minute:'2-digit'})}</span><PhoneIndicators/></div>
  <section className="lock-clock"><I.LockKeyhole/><time>{new Date(g.now).toLocaleTimeString('tr-TR',{hour:'2-digit',minute:'2-digit'})}</time><p>{date(g.now,{weekday:'long',day:'numeric',month:'long'})}</p></section>
  <section className="lock-notifications" aria-label="Bildirim önizlemeleri">{g.notifications.filter(n=>!n.read).slice(0,3).map(n=><article key={n.id}><AppGlyph app={n.app}/><div><b>{appMeta[n.app][0]}</b><span>{n.title}</span><p>{n.body}</p></div></article>)}{next&&<article><AppGlyph app="calendar"/><div><b>Sırada</b><span>{next.title}</span><p>{date(next.at)}</p></div></article>}</section>
  <button className="unlock" onClick={unlock}><I.ChevronUp/> Telefonu aç</button>
</main>}
function Status({openCenter}:{openCenter:()=>void}){const g=useGame(x=>x.game)!;return <header className="status"><span className="sim-time">{new Date(g.now).toLocaleTimeString('tr-TR',{hour:'2-digit',minute:'2-digit'})}</span><button className="desktop-home" onClick={()=>useGame.getState().open('home')}>MemleketOS</button><button className="status-icons" aria-label="Bildirim merkezini aç" onClick={openCenter}><PhoneIndicators/>{g.notifications.some(n=>!n.read)&&<b/>}</button></header>}
function NotificationCenter({g,close}:{g:State;close:()=>void}){const s=useGame();return <div className="shade" onClick={close}><section className="notification-center" role="dialog" aria-modal="true" aria-label="Bildirim merkezi" onClick={e=>e.stopPropagation()}><header><div><small>{date(g.now,{weekday:'long',day:'numeric',month:'long'})}</small><h2>Bildirimler</h2></div><button className="mark-all" onClick={()=>s.markAllRead()}>Tümünü oku</button><button aria-label="Kapat" onClick={close}><I.X/></button></header>{g.notifications.length===0?<p className="empty">Yeni bildirimin yok.</p>:g.notifications.map(n=><button className={n.read?'read':''} key={n.id} onClick={()=>{s.readNotification(n.id);s.open(n.app);close()}}><AppGlyph app={n.app}/><div><b>{appMeta[n.app][0]} · {n.title}</b><p>{n.body}</p><small>{new Date(n.at).toLocaleTimeString('tr-TR',{hour:'2-digit',minute:'2-digit'})}</small></div></button>)}</section></div>}
function AppGlyph({app}:{app:AppId}){const[,Icon,color]=appMeta[app];return <i className="app-glyph" style={{background:color}}><Icon/></i>}
function DesktopRail(){const s=useGame();return <aside className="rail"><Brand/><nav>{(Object.keys(appMeta)as AppId[]).map(a=>{const [n,Icon]=appMeta[a];return <button className={s.app===a?'active':''} key={a} onClick={()=>s.open(a)} title={n}><Icon/><span>{n}</span></button>})}</nav><button onClick={()=>s.setScreen('menu')}><I.LogOut/><span>Menü</span></button></aside>}
function AppHeader(){const s=useGame(),[name,Icon]=appMeta[s.app];return <header className="app-head"><button className="app-back" onClick={()=>s.open('home')} aria-label="Ana ekrana dön"><I.ChevronLeft/></button><div><Icon/><h2>{name}</h2></div><span className="app-head-spacer" aria-hidden="true"/></header>}
function SystemNavigation(){const s=useGame();if(s.app==='home')return null;return <footer className="system-nav"><button onClick={()=>s.open('home')} aria-label="Ana ekran"><span/></button></footer>}
function TimeSheet({g,close}:{g:State;close:()=>void}){const s=useGame();const next=g.events.filter(e=>!e.processed).sort((a,b)=>a.at.localeCompare(b.at))[0];const move=(days:number)=>{s.advance(days);close()};return <div className="shade sheet-shade" onClick={close}><section className="time-sheet" role="dialog" aria-modal="true" aria-label="Zaman akışı" onClick={e=>e.stopPropagation()}><i className="sheet-handle"/><header><div><small>AÇIK ZAMAN İLERLETME</small><h2>Zaman</h2></div><button onClick={close} aria-label="Kapat"><I.X/></button></header><p>Telefon kapanınca hayat ilerlemez. Bir süre seç.</p><div className="speed-row"><button onClick={()=>move(1/24)}><b>1 saat</b><span>Şimdi</span></button><button onClick={()=>move(1)}><b>1 gün</b><span>Yarın</span></button><button onClick={()=>move(4)}><b>4 gün</b><span>Yakın gelecek</span></button><button onClick={()=>move(12)}><b>12 gün</b><span>Uzun atlama</span></button></div><button className="next-event" onClick={()=>move(next?Math.max(1/24,(Date.parse(next.at)-Date.parse(g.now))/864e5):1)}><I.SkipForward/><span><b>Sonraki önemli olay</b><small>{next?.title||'Takvimde yeni olay yok'}</small></span></button></section></div>}
function Home({g,openTime}:{g:State;openTime:()=>void}){const s=useGame();const next=g.events.filter(e=>!e.processed).sort((a,b)=>a.at.localeCompare(b.at))[0];const dock:AppId[]=['chat','bank','market','news'];const apps=(Object.keys(appMeta)as AppId[]).filter(a=>a!=='home'&&!dock.includes(a));const badge=(a:AppId)=>a==='chat'?g.messages.filter(m=>!m.fromPlayer).length:a==='mail'?g.mails.filter(m=>!m.read).length:a==='career'?g.applications.length:0;return <div className="phone-home"><section className="personal-widget"><div><small>{date(g.now,{weekday:'long'})}</small><strong>{date(g.now,{day:'numeric',month:'long'})}</strong><span>{g.player.province}</span></div><button onClick={()=>s.open('calendar')}><I.CalendarDays/><span><small>SIRADA</small><b>{next?.title||'Bugün sakin'}</b></span></button></section><section className="mini-widgets"><button onClick={()=>s.open('bank')}><I.WalletCards/><span><small>CepBanka</small><b>{money(g.balance)}</b></span></button><button onClick={()=>s.open('school')}><I.GraduationCap/><span><small>Okulum</small><b>{next?.type==='exam'?next.title:'Derslerine göz at'}</b></span></button></section><button className="time-widget" onClick={openTime}><I.Clock3/><span><small>ZAMAN</small><b>Akışı yönet</b></span><I.ChevronRight/></button><div className="app-grid">{apps.map(a=>{const[n]=appMeta[a],count=badge(a);return <button key={a} onClick={()=>s.open(a)}><span className="icon-wrap"><AppGlyph app={a}/>{count>0&&<b className="badge">{count}</b>}</span><span>{n}</span></button>})}</div><section className="phone-dock" aria-label="Sık kullanılan uygulamalar">{dock.map(a=>{const[n]=appMeta[a],count=badge(a);return <button key={a} onClick={()=>s.open(a)} aria-label={n}><span className="icon-wrap"><AppGlyph app={a}/>{count>0&&<b className="badge">{count}</b>}</span></button>})}</section></div>}
function AppContent({g,openTime}:{g:State;openTime:()=>void}){const app=useGame(x=>x.app);if(app==='home')return <Home g={g} openTime={openTime}/>;if(app==='school')return <School g={g}/>;if(app==='bank')return <Bank g={g}/>;if(app==='market')return <Market g={g}/>;if(app==='career')return <Career g={g}/>;if(app==='chat')return <Chat g={g}/>;if(app==='stocks')return <Stocks g={g}/>;if(app==='archive')return <Archive g={g}/>;if(app==='calendar')return <Calendar g={g}/>;if(app==='notes')return <Notes g={g}/>;if(app==='settings')return <Settings g={g}/>;if(app==='feed')return <Feed g={g}/>;if(app==='mail')return <Mail g={g}/>;if(app==='news')return <News g={g}/>;if(app==='map')return <MapApp g={g}/>;return null}
const Card=({children}:{children:React.ReactNode})=><article className="card">{children}</article>;
function School({g}:{g:State}){const act=useGame(x=>x.study),[duration,setDuration]=useState(.5);const exams=g.events.filter(e=>e.type==='exam'&&!e.processed);return <div className="content"><div className="headline"><div><p>10. SINIF</p><h1>{g.education.school}</h1></div><strong>Enerji %{g.player.energy}</strong></div><div className="pills">{([[.5,'30 dk'],[1,'1 saat'],[2,'2 saat']] as const).map(([v,n])=><button className={duration===v?'active':''} key={v} onClick={()=>setDuration(v)}>{n}</button>)}</div>{exams.map(e=><Card key={e.id}><small>YAKLAŞAN SINAV · {date(e.at)}</small><b>{e.title}</b></Card>)}<h3>Dersler ve çalışma</h3><div className="cards">{Object.entries(g.education.knowledge).map(([k,v])=><Card key={k}><div className="row"><b>{k}</b><span>%{v}</span></div><progress value={v} max="100"/><button onClick={()=>act(k,duration)}>{duration===.5?'30 dakika':duration+' saat'} çalış</button></Card>)}</div><h3>Sonuçlar</h3><Card>{g.education.mockScores.length?g.education.mockScores.map((x,i)=><span key={i}>Sınav {i+1}: {x} </span>):'Henüz sonuç yok.'}</Card></div>}
function Bank({g}:{g:State}){return <div className="content"><section className="balance"><small>KULLANILABİLİR BAKİYE</small><h1>{money(g.balance)}</h1><p>TR00 •••• 1923</p></section><div className="stat-row"><Card><small>Aile geliri</small><b>{money(g.household.income)}</b></Card><Card><small>Aylık gider</small><b>{money(g.household.expenses)}</b></Card><Card><small>Birikim</small><b>{money(g.household.savings)}</b></Card></div><h3>Hesap hareketleri</h3>{g.ledger.map(x=><article className="transaction" key={x.id}><i className={x.amount>0?'plus':''}>{x.amount>0?<I.ArrowDownLeft/>:<I.ArrowUpRight/>}</i><div><b>{x.description}</b><small>{date(x.at)}</small></div><strong>{x.amount>0?'+':''}{money(x.amount)}</strong></article>)}</div>}
function Market({g}:{g:State}){const s=useGame(),[cat,setCat]=useState('Tümü'),[selected,setSelected]=useState<string>();const l=g.listings.find(x=>x.id===selected);if(l)return <div className="content"><button className="back" onClick={()=>setSelected(undefined)}><I.ArrowLeft/> İlanlara dön</button><Card><small>{l.category} · Kondisyon %{l.condition}</small><h1>{l.title}</h1><b className="price">{money(l.negotiation?.agreedPrice??l.price)}</b><p>Tahmini piyasa değeri: {money(l.marketValue)}<br/>Satıcı: {l.seller}<br/>{l.details}</p>{l.negotiation?.inspected&&<p><b>İnceleme:</b> {l.negotiation.revealedIssue||'Belirgin bir sorun görülmedi.'}</p>}<button onClick={()=>s.contact(l.id)}>Satıcıya sor</button><button onClick={()=>s.inspect(l.id)}>İncele</button><button onClick={()=>{const raw=prompt('Teklifiniz (TL)');if(raw)s.offer(l.id,Math.round(Number(raw.replace(',','.'))*100))}}>Teklif ver</button>{l.negotiation?.counterOffer&&<button onClick={()=>s.counter(l.id)}>Karşı teklifi kabul et ({money(l.negotiation.counterOffer)})</button>}<button onClick={()=>s.buy(l.id)}>Anlaşılan fiyata satın al</button></Card></div>;return <div className="content"><p className="fiction">Yerel hayatındaki kurgusal ilanlar.</p><div className="pills">{['Tümü','Vasıta','Emlak','Elektronik','Ev & Yaşam'].map(c=><button className={cat===c?'active':''} onClick={()=>setCat(c)} key={c}>{c}</button>)}</div><div className="listing-grid">{g.listings.filter(l=>l.status==='active'&&(cat==='Tümü'||l.category===cat)).map(l=><Card key={l.id}><button className="heart" onClick={()=>s.toggleFavorite(l.id)} aria-label="Favori"><I.Heart fill={l.favorite?'currentColor':'none'}/></button><small>{l.category} • Kondisyon %{l.condition}</small><h3>{l.title}</h3><b className="price">{money(l.price)}</b><p>{l.seller}</p><button onClick={()=>setSelected(l.id)}>İlanı aç</button></Card>)}</div></div>}
function Career({g}:{g:State}){const apply=useGame(x=>x.apply);return <div className="content"><div className="headline"><div><p>FIRSATLAR</p><h1>{g.player.province} için ilanlar</h1></div><strong>{g.applications.length} başvuru</strong></div><div className="cards">{g.jobs.map(j=>{const c=g.companies.find(x=>x.id===j.companyId)!,a=g.applications.find(x=>x.jobId===j.id);return <Card key={j.id}><small>{c.name} • {j.city}</small><h3>{j.position}</h3><p>{j.workType} · {j.education}<br/>{j.skills.join(', ')}</p><b>{money(j.salary)} / ay</b>{a?.state==='offer'?<><button onClick={()=>useGame.getState().offerDecision(a.id,true)}>Teklifi kabul et</button><button onClick={()=>useGame.getState().offerDecision(a.id,false)}>Reddet</button></>:<button disabled={!!a} onClick={()=>apply(j.id)}>{a?`Durum: ${a.state}`:'Başvur'}</button>}</Card>})}</div></div>}
function Chat({g}:{g:State}){const send=useGame(x=>x.send),[active,setActive]=useState(g.npcs[0]?.id),[text,setText]=useState('');const n=g.npcs.find(x=>x.id===active)!;return <div className="chat-layout"><aside>{g.npcs.map(n=><button className={active===n.id?'active':''} onClick={()=>setActive(n.id)} key={n.id}><Avatar n={n.name}/><div><b>{n.name}</b><small>{n.role}</small></div></button>)}</aside><section><header><Avatar n={n.name}/><div><b>{n.name}</b><small>Sıcaklık %{n.relationship.warmth}</small></div></header><div className="bubbles">{g.messages.filter(m=>m.npcId===active).map(m=><p className={m.fromPlayer?'mine':''} key={m.id}>{m.text}</p>)}</div><form onSubmit={e=>{e.preventDefault();if(text.trim()){send(active,text);setText('')}}}><input aria-label="Mesaj" value={text} onChange={e=>setText(e.target.value)} placeholder="Bir mesaj yaz…"/><button><I.Send/></button></form></section></div>}
function Avatar({n}:{n:string}){return <i className="avatar">{n.split(' ').map(x=>x[0]).slice(0,2)}</i>}
function Stocks({g}:{g:State}){const trade=useGame(x=>x.trade);return <div className="content"><p className="fiction">Gerçek para veya şirket içermez. Kurgusal piyasa simülasyonudur.</p><div className="stat-row"><Card><small>NAKİT</small><b>{money(g.balance)}</b></Card><Card><small>PORTFÖY</small><b>{money(Object.entries(g.holdings).reduce((a,[id,h])=>a+(g.companies.find(c=>c.id===id)?.price||0)*h.quantity,0))}</b></Card></div><div className="cards">{g.companies.slice(0,16).map(c=><Card key={c.id}><small>{c.sector}</small><h3>{c.name}</h3><b className="price">{money(c.price)}</b><p>Sağlık %{c.health} · Büyüme %{c.growth}<br/>Portföy: {g.holdings[c.id]?.quantity||0} adet</p><button onClick={()=>trade(c.id,1)}>1 adet al</button>{(g.holdings[c.id]?.quantity||0)>0&&<button onClick={()=>trade(c.id,-1)}>Sat</button>}</Card>)}</div></div>}
function Archive({g}:{g:State}){return <div className="content timeline"><h1>{g.player.name}’in Hayat Arşivi</h1>{g.archive.sort((a,b)=>b.at.localeCompare(a.at)).map((x,i)=><article key={i}><i/><div><small>{date(x.at)} • {x.category}</small><p>{x.text}</p></div></article>)}</div>}
function Calendar({g}:{g:State}){return <div className="content"><h1>Yaklaşanlar</h1>{g.events.sort((a,b)=>a.at.localeCompare(b.at)).map(e=><article className={`event ${e.processed?'done':''}`} key={e.id}><time>{date(e.at,{day:'numeric',month:'short'})}</time><div><b>{e.title}</b><small>{e.processed?'Tamamlandı':e.important?'Önemli olay':'Planlandı'}</small></div></article>)}</div>}
function Notes({g}:{g:State}){const set=useGame(x=>x.setNotes);return <div className="content notes"><label htmlFor="notes">Kişisel notların</label><textarea id="notes" value={g.notes} onChange={e=>set(e.target.value)} placeholder="Çalışma planı, hedefler, hatırlatmalar…"/><small>Otomatik olarak yerel kayda eklenir.</small></div>}
function Settings({g}:{g:State}){const s=useGame();return <div className="content"><h1>Ayarlar</h1>{([['sound','Sesler'],['reducedMotion','Azaltılmış hareket'],['largeText','Büyük metin']]as const).map(([k,n])=><button className="setting" key={k} onClick={()=>s.setting(k,!g.settings[k])}><span>{n}</span><b>{g.settings[k]?'Açık':'Kapalı'}</b></button>)}<h3>Duvar kâğıdı</h3><div className="pills">{([['city','Şehir'],['coast','Sahil'],['simple','Sade']]as const).map(([v,n])=><button className={g.settings.wallpaper===v?'active':''} onClick={()=>s.wallpaper(v)} key={v}>{n}</button>)}</div><Card><I.ShieldCheck/><h3>Gizlilik</h3><p>{tr.privacy}</p></Card><Card><h3>Yerel kayıt</h3><p>İçe aktarılan dosya önce sürümlenir ve katı şemayla doğrulanır. Hatalı dosya mevcut hayatı değiştirmez.</p><button onClick={()=>void s.save()}>Şimdi kaydet</button><button onClick={()=>void s.exportSave()}>JSON dışa aktar</button><label className="import-button">JSON içe aktar<input type="file" accept="application/json" onChange={e=>{const f=e.target.files?.[0];if(f)void s.importSave(f)}}/></label></Card></div>}
function Feed({g}:{g:State}){const s=useGame();return <div className="content feed">{g.posts.map(p=>{const n=g.npcs.find(x=>x.id===p.npcId)!;return <Card key={p.id}><header><Avatar n={n.name}/><div><b>{n.name}</b><small>{date(p.at)}</small></div></header><p>{p.text}</p><button aria-label={p.liked?'Beğeniyi kaldır':'Beğen'} onClick={()=>s.like(p.id)}><I.Heart fill={p.liked?'currentColor':'none'}/> {p.likes}</button><details><summary>{p.comments.length} yorum</summary>{p.comments.map(c=><p key={c.id}><b>{c.authorId==='player'?'Sen':'Yakın çevre'}:</b> {c.text}</p>)}<form onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget),v=String(f.get('comment')||'');s.comment(p.id,v);e.currentTarget.reset()}}><input name="comment" aria-label="Yorum"/><button>Yaz</button></form></details></Card>})}</div>}
function Mail({g}:{g:State}){const s=useGame(),[open,setOpen]=useState<string>();const active=g.mails.find(m=>m.id===open);if(active)return <div className="content"><button className="back" onClick={()=>setOpen(undefined)}><I.ArrowLeft/> Gelen kutusu</button><h1>{active.subject}</h1><small>{active.sender} · {date(active.at)}</small><p>{active.body}</p>{active.app&&<button onClick={()=>s.open(active.app!)}>İlgili uygulamayı aç</button>}</div>;return <div className="content"><h1>Gelen kutusu</h1>{g.mails.map(m=><button className={`mail ${m.read?'read':''}`} key={m.id} onClick={()=>{s.readMail(m.id);setOpen(m.id)}}><I.Mail/><div><b>{m.sender}</b><strong>{m.subject}</strong><p>{m.body}</p></div><small>{date(m.at)}</small></button>)}</div>}
function News({g}:{g:State}){return <div className="content"><p className="fiction">Kurgusal haber · Gerçek kişi, şirket veya veri içermez.</p>{g.news.length?g.news.map(n=><Card key={n.id}><small>{n.category} · {date(n.at)}</small><h3>{n.title}</h3><p>{n.body}</p></Card>):<Card><h3>Dünya henüz sakin</h3><p>Zaman ilerledikçe şirket, okul ve şehir gelişmeleri burada oluşur.</p></Card>}</div>}
function MapApp({g}:{g:State}){const s=useGame(),[dest,setDest]=useState(''),[mode,setMode]=useState('Yürü');const places=[['Ev',I.House],['Okul',I.GraduationCap],['Kafe',I.Coffee],['Market',I.ShoppingBasket],['Hastane',I.Hospital]] as const;return <div className="content map"><p>Şu an: <b>{g.location}</b></p><div className="map-canvas">{places.map(([n,Icon],i)=><button style={{left:`${15+(i*19)%75}%`,top:`${20+(i*23)%65}%`}} onClick={()=>setDest(n)} key={n}><Icon/><span>{n}</span></button>)}</div><Card><h3>{dest||'Bir varış noktası seç'}</h3><div className="pills">{['Yürü','Otobüs','Minibüs','Taksi',...(g.vehicles.length?['Aracım']:[])].map(m=><button className={mode===m?'active':''} key={m} onClick={()=>setMode(m)}>{m}</button>)}</div><button disabled={!dest||dest===g.location} onClick={()=>s.travel(dest,mode)}>Yola çık</button></Card></div>}
