import { ChevronLeft, ChevronRight } from "lucide-react";
import type { State } from "../../../core/model";
import { date } from "../../format";
export const monthKey=(iso:string)=>iso.slice(0,7);
const monthDate=(key:string)=>new Date(`${key}-01T00:00:00.000Z`);
const shiftMonth=(key:string,delta:number)=>{const d=monthDate(key);d.setUTCMonth(d.getUTCMonth()+delta);return d.toISOString().slice(0,7)};
const eventClass=(type:string,important:boolean)=>type==="exam"?"exam":type==="interview"?"interview":type==="salary"?"salary":type==="bill"?"bill":important?"important":"other";
export function MonthView({game,viewedMonth,selectedDate,onMonth,onSelectDate,onOpenEvent}:{game:State;viewedMonth:string;selectedDate:string;onMonth:(v:string)=>void;onSelectDate:(v:string)=>void;onOpenEvent:(id:string)=>void}){const first=monthDate(viewedMonth);const days=new Date(Date.UTC(first.getUTCFullYear(),first.getUTCMonth()+1,0)).getUTCDate();const offset=(first.getUTCDay()+6)%7;const cells=Array.from({length:offset+days},(_,i)=>i<offset?null:i-offset+1);const monthEvents=game.events.filter(e=>monthKey(e.at)===viewedMonth);const selectedEvents=game.events.filter(e=>e.at.slice(0,10)===selectedDate).sort((a,b)=>a.at.localeCompare(b.at));const label=new Intl.DateTimeFormat("tr-TR",{month:"long",year:"numeric",timeZone:"UTC"}).format(first);
 return <div className="month-view"><div className="month-navigation"><button aria-label="Önceki ay" onClick={()=>onMonth(shiftMonth(viewedMonth,-1))}><ChevronLeft/></button><h2>{label}</h2><button aria-label="Sonraki ay" onClick={()=>onMonth(shiftMonth(viewedMonth,1))}><ChevronRight/></button></div>{viewedMonth!==monthKey(game.now)&&<button className="calendar-today" onClick={()=>{onMonth(monthKey(game.now));onSelectDate(game.now.slice(0,10))}}>Bugüne dön</button>}
 <div className="weekday-row" aria-hidden="true">{["Pzt","Sal","Çar","Per","Cum","Cmt","Paz"].map(x=><span key={x}>{x}</span>)}</div><div className="month-grid">{cells.map((day,i)=>day===null?<span className="blank" key={`b${i}`}/>:(()=>{const key=`${viewedMonth}-${String(day).padStart(2,"0")}`;const events=monthEvents.filter(e=>e.at.slice(0,10)===key);const aria=`${new Intl.DateTimeFormat("tr-TR",{day:"numeric",month:"long",timeZone:"UTC"}).format(new Date(`${key}T00:00:00Z`))}, ${events.length} etkinlik`;return <button key={key} aria-label={aria} aria-pressed={selectedDate===key} className={`${key===game.now.slice(0,10)?"sim-today":""} ${selectedDate===key?"selected":""}`} onClick={()=>onSelectDate(key)}><b>{day}</b><span>{events.slice(0,3).map(e=><i key={e.id} className={eventClass(e.type,e.important)}/>)}</span></button>})())}</div>
 <section className="selected-day"><h3>{date(`${selectedDate}T00:00:00.000Z`,{weekday:"long",day:"numeric",month:"long",timeZone:"UTC"})}</h3>{selectedEvents.length?selectedEvents.map(e=><button key={e.id} onClick={()=>onOpenEvent(e.id)}><i className={eventClass(e.type,e.important)}/><span><b>{e.title}</b><small>{date(e.at,{hour:"2-digit",minute:"2-digit",timeZone:"UTC"})}</small></span><strong>›</strong></button>):<p>Bu gün için planlanmış bir etkinlik yok.</p>}</section></div>}
