import {z} from 'zod';
export type Money=number; export type AppId='home'|'archive'|'school'|'career'|'bank'|'market'|'chat'|'feed'|'mail'|'news'|'stocks'|'calendar'|'map'|'notes'|'settings';
export interface Traits{discipline:number;confidence:number;socialSkill:number;academicAbility:number;financialLiteracy:number;resilience:number;creativity:number;adaptability:number;fitness:number}
export interface NPC{id:string;name:string;age:number;role:string;personality:string;education:string;occupation:string;income:Money;goal:string;lifeStage:string;closeness:'close'|'relevant'|'distant';relationship:{familiarity:number;warmth:number;trust:number;tension:number};memories:Memory[]}
export interface Memory{id:string;kind:string;at:string;impact:number;summary:string}
export interface Ledger{id:string;at:string;amount:Money;kind:'income'|'expense'|'transfer'|'investment';description:string;balanceAfter:Money}
export interface GameEvent{id:string;at:string;type:string;title:string;important:boolean;processed?:boolean;entityIds?:string[]}
export interface Notification{id:string;at:string;app:AppId;title:string;body:string;read:boolean}
export interface Listing{id:string;category:'Vasıta'|'Emlak'|'Elektronik'|'Ev & Yaşam';title:string;price:Money;marketValue:Money;condition:number;seller:string;favorite:boolean;status:'active'|'sold'|'expired';details:string;hiddenIssue?:string}
export interface Company{id:string;name:string;sector:string;size:string;health:number;growth:number;reputation:number;hiringDemand:number;layoffRisk:number;price:Money;priceHistory:number[]}
export interface Job{id:string;companyId:string;position:string;city:string;salary:Money;education:string;experience:number;skills:string[];workType:string}
export interface Application{id:string;jobId:string;state:'submitted'|'viewed'|'rejection'|'no response'|'interview'|'later stage'|'offer'|'accepted'|'withdrawn';updatedAt:string}
export interface Message{id:string;npcId:string;at:string;text:string;fromPlayer:boolean}
export interface State{schemaVersion:2;simulationVersion:string;worldSeed:number;characterSeed:number;rngState:number;id:string;createdAt:string;updatedAt:string;now:string;speed:0|1|4|12;player:{name:string;birthDate:string;province:string;district:string;traits:Traits;energy:number;stress:number;mood:number;health:number;social:number};household:{memberIds:string[];income:Money;expenses:Money;savings:Money;socioeconomic:string;housing:{kind:string;province:string;district:string;rent:Money;size:number;quality:number;commute:number;costs:Money}};npcs:NPC[];balance:Money;ledger:Ledger[];events:GameEvent[];notifications:Notification[];archive:{at:string;category:string;text:string}[];education:{stage:'highSchool'|'yks'|'university'|'graduated';school:string;grade:number;knowledge:Record<string,number>;attendance:number;consistency:number;mockScores:number[];gpa:number;credits:number;program?:string};companies:Company[];jobs:Job[];applications:Application[];employment?:{jobId:string;performance:number;startedAt:string};listings:Listing[];vehicles:{listingId:string;title:string;value:Money;condition:number}[];messages:Message[];posts:{id:string;npcId:string;at:string;text:string;likes:number;liked:boolean}[];mails:{id:string;at:string;sender:string;subject:string;body:string;read:boolean}[];holdings:Record<string,{quantity:number;cost:Money}>;notes:string;settings:{sound:boolean;reducedMotion:boolean;largeText:boolean};processedEventIds:string[]}
export const saveSchema=z.object({schemaVersion:z.literal(2),simulationVersion:z.string(),worldSeed:z.number().int(),characterSeed:z.number().int(),rngState:z.number().int(),id:z.string(),createdAt:z.string(),updatedAt:z.string(),now:z.string(),speed:z.union([z.literal(0),z.literal(1),z.literal(4),z.literal(12)])}).passthrough();
export function assertMoney(n:number){if(!Number.isSafeInteger(n))throw new Error('Güvenli para sınırı aşıldı');}
