import{describe,it,expect}from'vitest';
import{RNG}from'./rng';
import{createLife,advance,advanceMinutes,study,calculateYks,buyListing,trade,postLedger,addMemory,sendMessage,togglePostLike,commentPost,applyJob,negotiate,inspectListing,travel,markNotification,attendInterview,missInterview,decideOffer,unreadCounts,markConversationRead}from'./simulation';

describe('deterministic simulation',()=>{
 it('repeats RNG streams and life generation',()=>{const a=new RNG(42),b=new RNG(42);expect([a.next(),a.next()]).toEqual([b.next(),b.next()]);expect(createLife({seed:8})).toEqual(createLife({seed:8}))});
 it('processes every event exactly once',()=>{const s=createLife({seed:3});advance(s,7);const ledger=s.ledger.length;advance(s,1);expect(s.ledger.length).toBe(ledger);expect(new Set(s.processedEventIds).size).toBe(s.processedEventIds.length)});
 it('stops a long skip at an unresolved important decision',()=>{const s=createLife({seed:31}),at=new Date(Date.parse(s.now)+60*60000).toISOString();s.events.push({id:'choice',at,type:'choice',title:'Karar',important:true,requiresInput:true});advance(s,12);expect(s.now).toBe(at);expect(s.events.find(e=>e.id==='choice')?.processed).not.toBe(true)});
 it('applies only actual study effects when an input event interrupts a session',()=>{const s=createLife({seed:61}),before=s.education.knowledge.Matematik,energy=s.player.energy,at=new Date(Date.parse(s.now)+30*60000).toISOString();s.events.push({id:'study-block',at,type:'choice',title:'Görüşme',important:true,requiresInput:true});const result=study(s,'Matematik',2);expect(result.advancedMinutes).toBe(30);expect(result.interrupted).toBe(true);expect(s.education.knowledge.Matematik-before).toBeLessThanOrEqual(1);expect(energy-s.player.energy).toBe(2.5);expect(s.now).toBe(at)});
 it('does not arrive or charge when travel is interrupted',()=>{const s=createLife({seed:62}),balance=s.balance,energy=s.player.energy,at=new Date(Date.parse(s.now)+10*60000).toISOString();s.events.push({id:'travel-block',at,type:'choice',title:'Görüşme',important:true,requiresInput:true});const result=travel(s,'Okul','Otobüs');expect(result.advancedMinutes).toBe(10);expect(s.location).toBe('Ev');expect(s.balance).toBe(balance);expect(s.player.energy).toBe(energy);expect(s.notifications[0].title).toBe('Yolculuk yarıda kaldı')});
 it('uninterrupted study and travel apply their full consequences',()=>{const s=createLife({seed:63}),knowledge=s.education.knowledge.Matematik,balance=s.balance;const studied=study(s,'Matematik',2);expect(studied.advancedMinutes).toBe(120);expect(s.education.knowledge.Matematik).toBeGreaterThan(knowledge);const trip=travel(s,'Okul','Otobüs');expect(trip.advancedMinutes).toBe(22);expect(s.location).toBe('Okul');expect(s.balance).toBe(balance-2000)});
 it('future actions work after resolving a blocker without duplicate processing',()=>{const s=createLife({seed:64}),at=new Date(Date.parse(s.now)+10*60000).toISOString();s.events.push({id:'block-once',at,type:'choice',title:'Karar',important:true,requiresInput:true});travel(s,'Okul','Otobüs');const blocker=s.events.find(e=>e.id==='block-once')!;blocker.requiresInput=false;const result=travel(s,'Okul','Otobüs');expect(result.advancedMinutes).toBe(22);expect(s.location).toBe('Okul');expect(s.processedEventIds.filter(id=>id==='block-once')).toHaveLength(1)});
 it('studying across a due event uses the central scheduler',()=>{const s=createLife({seed:2});s.events[0].at=new Date(Date.parse(s.now)+30*60000).toISOString();study(s,'Matematik',2);expect(s.events[0].processed).toBe(true);expect(s.education.mockScores).toHaveLength(1);expect(calculateYks(s)).toEqual(calculateYks(s))});
 it('travel across a due event uses the central scheduler',()=>{const s=createLife({seed:33});s.events[0].at=new Date(Date.parse(s.now)+10*60000).toISOString();travel(s,'Okul','Otobüs');expect(s.events[0].processed).toBe(true);expect(s.location).toBe('Okul')});
 it('progresses applications by elapsed time and stops at interview',()=>{const s=createLife({seed:24});s.player.traits.socialSkill=100;s.player.traits.discipline=100;s.companies[0].hiringDemand=100;applyJob(s,s.jobs[0].id);advance(s,12);expect(s.applications[0].state).toBe('interview');expect(s.events.find(e=>e.type==='interview')?.at).toBe(s.now)});
 it('attends an interview deterministically and later produces an offer',()=>{const a=createLife({seed:40}),b=createLife({seed:40});for(const s of[a,b]){s.player.traits.socialSkill=100;s.player.traits.discipline=100;s.companies[0].hiringDemand=100;s.companies[0].health=100;s.player.traits.confidence=100;applyJob(s,s.jobs[0].id);advance(s,12);attendInterview(s,s.applications[0].id,'prepared');advance(s,2)}expect(a.applications[0]).toEqual(b.applications[0]);expect(a.applications[0].state).toBe('offer')});
 it('missing an interview rejects the application',()=>{const s=createLife({seed:41});s.player.traits.socialSkill=100;s.player.traits.discipline=100;s.companies[0].hiringDemand=100;applyJob(s,s.jobs[0].id);advance(s,12);missInterview(s,s.applications[0].id);expect(s.applications[0].state).toBe('rejection')});
 it('accepts an offer, creates work and posts scheduled salary',()=>{const s=createLife({seed:42}),a={id:'offer-app',jobId:s.jobs[0].id,state:'offer' as const,updatedAt:s.now,statusUnread:true};s.applications.push(a);decideOffer(s,a.id,true);expect(s.employment).toBeTruthy();expect(s.events.some(e=>e.type==='shift')).toBe(true);const before=s.balance;advance(s,30);expect(s.balance).toBe(before+s.jobs[0].salary-85000);expect(s.ledger[0].kind).toBe('income')});
 it('declines an offer cleanly',()=>{const s=createLife({seed:43}),a={id:'offer-app',jobId:s.jobs[0].id,state:'offer' as const,updatedAt:s.now,statusUnread:true};s.applications.push(a);decideOffer(s,a.id,false);expect(a.state).toBe('declined');expect(s.employment).toBeUndefined();expect(s.mails[0].subject).toBe('Teklif yanıtı')});
 it('tracks persistent chat unread state and badge semantics',()=>{const s=createLife({seed:44}),id=s.npcs[0].id;sendMessage(s,id,'Selam');expect(unreadCounts(s).chat).toBe(2);markConversationRead(s,id);expect(unreadCounts(s).chat).toBe(0);expect(unreadCounts(s).mail).toBe(1)});
 it('an apology reduces tension and restores trust',()=>{const s=createLife({seed:45}),n=s.npcs[0];n.relationship.tension=50;const trust=n.relationship.trust;sendMessage(s,n.id,'Özür dilerim');expect(n.relationship.tension).toBe(42);expect(n.relationship.trust).toBeGreaterThan(trust)});
 it('persists feed reactions, player comments and bounded NPC comments',()=>{const s=createLife({seed:23}),p=s.posts[0];togglePostLike(s,p.id);commentPost(s,p.id,'Kolay gelsin!');expect(p.liked).toBe(true);expect(p.comments[0].text).toBe('Kolay gelsin!');expect(p.comments.length).toBeLessThanOrEqual(12)});
 it('negotiates, inspects and purchases at agreed price',()=>{const s=createLife({seed:25}),l=s.listings.find(x=>x.category==='Elektronik')!;s.balance=10_000_000;negotiate(s,l.id,l.marketValue);inspectListing(s,l.id);const before=s.balance;buyListing(s,l.id);expect(s.balance).toBe(before-(l.negotiation?.agreedPrice??l.price))});
 it('preserves ledger integrity and investment accounting',()=>{const s=createLife({seed:4}),before=s.balance;postLedger(s,-100,'test','expense');expect(s.balance).toBe(before-100);const c=s.companies[0];s.balance=c.price*2;trade(s,c.id,1);trade(s,c.id,-1);expect(s.holdings[c.id].quantity).toBe(0)});
 it('reads only the selected notification',()=>{const s=createLife({seed:27});s.notifications.push({...s.notifications[0],id:'second'});markNotification(s,'welcome');expect(s.notifications.find(n=>n.id==='second')?.read).toBe(false)});
 it('adds and prunes relationship memories',()=>{const s=createLife({seed:7}),n=s.npcs[0];for(let i=0;i<30;i++)addMemory(s,n.id,'workedTogether',String(i),1);expect(n.memories).toHaveLength(20)});
 it('advanceMinutes rejects backwards time indirectly and advances exact minutes',()=>{const s=createLife({seed:50}),before=Date.parse(s.now);advanceMinutes(s,5);expect(Date.parse(s.now)-before).toBe(300000)});
});
